require 'sinatra'
require 'sinatra/reloader'

this_dir = File.expand_path(File.dirname(__FILE__))
autogenerated_pb_dir = File.join(this_dir, 'autogenerated_pb')
$LOAD_PATH.unshift(autogenerated_pb_dir) unless $LOAD_PATH.include?(autogenerated_pb_dir)

require 'grpc'
require 'products_services_pb'

configure do
  enable :reloader
  set :strict_paths, false
end

get '/' do
  content_type :json
  {
    app: 'GRPC studies - Apps Ruby - Client - Homepage'
  }.to_json
end

get '/api/products' do
  content_type :json

  # https://rubydoc.info/gems/grpc/GRPC/GenericService/Dsl:rpc_stub_class
  # https://github.com/grpc/grpc/blob/v1.63.0/src/ruby/lib/grpc/generic/service.rb#L148-L191
  stub = ProductService::Stub.new(ENV['GRPC_SERVER'], :this_channel_is_insecure)

  error = nil
  data = nil

  data = begin
           stub.list_all(Empty.new)
         rescue GRPC::BadStatus => e
           error = "GRPC error #{e.code} | Details #{e.details} | From Ruby"
           nil
         end
  {
    app: 'GRPC studies - Apps Ruby - Client - GET /api/products (GRPC ListAll)',
    error: error,
    data: data
  }.to_json
end

get '/api/products/:id' do
  content_type :json

  id = params['id'].to_i

  stub = ProductService::Stub.new(ENV['GRPC_SERVER'], :this_channel_is_insecure)

  error = nil
  data = nil

  data = begin
           stub.get(ProductRequestId.new(id: id))
         rescue GRPC::BadStatus => e
           error = "GRPC error #{e.code} | Details #{e.details} | From Ruby"
           nil
         end

  {
    app: 'GRPC studies - Apps Ruby - Client - GET /api/products/:id (GRPC Get)',
    error: error,
    data: data
  }.to_json
end

post '/api/products' do
  content_type :json

  payload = JSON.parse(request.body.read)

  stub = ProductService::Stub.new(ENV['GRPC_SERVER'], :this_channel_is_insecure)

  error = nil
  data = nil

  data = begin
           stub.insert(Product.new(name: payload['name'], description: payload['description']))
         rescue GRPC::BadStatus => e
           error = "GRPC error #{e.code} | Details #{e.details} | From Ruby"
           nil
         end

  {
    app: 'GRPC studies - Apps Ruby - Client - POST /api/products (GRPC Insert)',
    error: error,
    data: data
  }.to_json
end

put '/api/products/:id' do
  content_type :json

  id = params['id'].to_i
  payload = JSON.parse(request.body.read)

  stub = ProductService::Stub.new(ENV['GRPC_SERVER'], :this_channel_is_insecure)

  error = nil
  data = nil

  data = begin
           stub.update(Product.new(id: id, name: payload['name'], description: payload['description']))
         rescue GRPC::BadStatus => e
           error = "GRPC error #{e.code} | Details #{e.details} | From Ruby"
           nil
         end

  {
    app: 'GRPC studies - Apps Ruby - Client - PUT /api/products/:id (GRPC Update)',
    error: error,
    data: data
  }.to_json
end

delete '/api/products/:id' do
  content_type :json

  id = params['id'].to_i

  stub = ProductService::Stub.new(ENV['GRPC_SERVER'], :this_channel_is_insecure)

  error = nil
  data = nil

  data = begin
           stub.delete(ProductRequestId.new(id: id))
         rescue GRPC::BadStatus => e
           error = "GRPC error #{e.code} | Details #{e.details} | From Ruby"
           nil
         end

  {
    app: 'GRPC studies - Apps Ruby - Client - DELETE /api/products/:id (GRPC Delete)',
    error: error,
    data: data
  }.to_json
end
