# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto

require 'google/protobuf'


descriptor_data = "\n\x0eproducts.proto\"\x07\n\x05\x45mpty\"8\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"d\n\x16ProductListAllResponse\x12\x1e\n\x06status\x18\x01 \x01(\x0e\x32\x0e.RpcStatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x19\n\x07results\x18\x03 \x03(\x0b\x32\x08.Product\"\x1e\n\x10ProductRequestId\x12\n\n\x02id\x18\x01 \x01(\x03*g\n\rRpcStatusCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x14\n\x10VALIDATION_ERROR\x10\x01\x12\x18\n\x14\x41UTHENTICATION_ERROR\x10\x02\x12\x19\n\x15INTERNAL_SERVER_ERROR\x10\x03\x32\xcb\x01\n\x0eProductService\x12,\n\x07ListAll\x12\x06.Empty\x1a\x17.ProductListAllResponse\"\x00\x12$\n\x03Get\x12\x11.ProductRequestId\x1a\x08.Product\"\x00\x12\x1e\n\x06Insert\x12\x08.Product\x1a\x08.Product\"\x00\x12\x1e\n\x06Update\x12\x08.Product\x1a\x08.Product\"\x00\x12%\n\x06\x44\x65lete\x12\x11.ProductRequestId\x1a\x06.Empty\"\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Empty").msgclass
Product = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Product").msgclass
ProductListAllResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ProductListAllResponse").msgclass
ProductRequestId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ProductRequestId").msgclass
RpcStatusCode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RpcStatusCode").enummodule
